### ISSUE TITLE
Should we add MoneyFormat?

### ISSUE THREAD

**Issue by rodolfobandeira** [dblock/iex-ruby-client#11]
This is not an issue, is more a question.  I was [working to implement](https://github.com/rodolfobandeira/iex-ruby-client/tree/add-key-stats) the `KeyStats` resource when I came across the following property:

`"marketCap": 751627174400`

The same way we created some custom properties like `change_percent_s` where it returns a formatted version like `+NN.NN%`, I'm wondering if we could do the same to have a better format like:

- `"market_cap_s": "7,516,271,744.00"`
- `"market_cap_dollar": $7,516,271,744.00`
- `"market_cap_short": 7.5 Billion`
- `"market_cap_shorter": 7.5 B`

Anyways, what do you think? Worth investing some time? Do you know a nice lib for Money objects?

Thanks!

**Comment by dblock** [comment]
The idea behind those `_s` methods is to transform a number into a string with meaning. For example the change in percent of "0.75" becoming "+75%", especially meaningful with + and - as this is a fairly "standard" way to represent the change in % as a string.

For market cap though the value is in cents (or dollars), and by adding various formats you're not adding anything meaningful, so I would not do it, especially that for a library we'd then want this for every single dollar value.

All that said, wouldn't it be nice for developers to not have to worry about formatting and be able to do `any_field_dollars` or `any_field_rounded_dollars` (probably better naming than short and shorter)? The answer is obviously yes, so I would find a library that does that and implement this as an extension for any field via `method_missing`. Any method that ends with `_dollars` would call a format function. It would also need to support other currencies.

And so since you asked, https://github.com/artsy/money_helper :)
