### ISSUE TITLE
Website url

### ISSUE THREAD

**Issue by deveshp530** [dblock/iex-ruby-client#74]
I am trying to show the website url on my application, but it is not showing the correct link. 
![Screen Shot 2020-05-19 at 2 42 08 PM](https://user-images.githubusercontent.com/31877457/82381382-f88cfc00-99de-11ea-8e2e-344005916fc6.png)

Not sure why this is happening

**Comment by dblock** [comment]
This looks similar to https://github.com/dblock/iex-ruby-client/issues/73. Can you please post a repro of this?

**Comment by deveshp530** [comment]
> This looks similar to #73. Can you please post a repro of this?

https://github.com/deveshp530/stock-app

**Comment by dblock** [comment]
@deveshp530 I failed to run your app, after `bundle install`, `yarn` and `rails assets:precompile` for me it fails at

```
Compiling...
Compilation failed:
/Users/dblock/source/stock-app/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

```

Please provide detailed instructions on how to reproduce this problem.

**Comment by dblock** [comment]
I managed to make it work. 

This happens because you're running against [IEX sandbox](https://intercom.help/iexcloud/en/articles/2915433-testing-with-the-iex-cloud-sandbox).

"Test data randomization  

Data returned from sandbox API calls is scrambled and should not be used for purposes outside of testing. However, test calls return the same properties and data types as they will in production, which allows for full functionality testing. 

Many endpoints that return a date — such as Historical Prices — will have the date accurately returned in the sandbox environment, so as to allow users to test out charting functionality within their application or project. "

**Comment by deveshp530** [comment]
So just turn sandbox off and update publish token?

**Comment by dblock** [comment]
> So just turn sandbox off and update publish token?

Yes.

**Comment by dblock** [comment]
I'm going to stop recommending the sandbox environment as the default in the README, it confuses new users, https://github.com/dblock/iex-ruby-client/pull/75.
